// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egivhuxniognbafqijmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnaXZodXhuaW9nbmJhZnFpam1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjEyODQsImV4cCI6MjA3NDEzNzI4NH0.LOnI7mnMungqJcXAp-z35RQ4wGPet5UnT64DRy2mL2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});